
spring:
  datasource:
    url: jdbc:mysql://backjin.iptime.org:3306/study_test_db
    username: app_user
    password: 'wlsdnr7^^'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  main:
    allow-bean-definition-overriding: true

# Logging 설정
logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF

jwt:
  secret: "c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK"
  expiration: 8640000
