spring:
  application:
    name: hh3week

  datasource:
    url: 'jdbc:h2:file:/db/H2/hh3week;AUTO_SERVER=true'
    username: 'sa'
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true  # SQL? ??
    properties:
      hibernate:
        format_sql: false  # SQL? ?? ?? ??


  jwt:
    secret: "YourSecretKeyForJWTGenerationWhichShouldBeVerySecureAndLongEnough"
    expiration: 86400000 # 24시간 (밀리초 단위)