# 실제 운영될 DB 프로필
spring:
  cache:
    type: redis
  redis:
    cache:
      redis:
        use-key-prefix: true
  data:
    redis:
      host: backjin.iptime.org
      port: 6379
      password:

  kafka:
    bootstrap-servers: backjin.iptime.org:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: reservation-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

  application:
    name: hh3week

  datasource:
    url: jdbc:mysql://backjin.iptime.org:3306/study_db
    username: app_user
    password: 'wlsdnr7^^' # 특수 문자가 포함되어 있으므로 따옴표로 감쌌습니다.
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30  # 최대 커넥션 수
      minimum-idle: 10       # 최소 대기 커넥션 수
      idle-timeout: 600000   # 유휴 타임아웃 시간
      connection-timeout: 60000  # 연결 대기 시간 (60초)
      max-lifetime: 1800000  # 최대 수명 (30분)
      leak-detection-threshold: 2000  # 커넥션 누수 탐지 (2초 이상 열린 커넥션)

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false # SQL 로그를 콘솔에 출력합니다.
    properties:
      hibernate:
        format_sql: false # SQL 로그의 형식을 포맷하지 않습니다.
      dialect: org.hibernate.dialect.MySQL8Dialect
      connection:
        isolation: 2


  main:
    allow-bean-definition-overriding: true


# Logging 설정
#logging:
#  level:
#    org.hibernate.SQL: OFF
#    org.hibernate.type.descriptor.sql.BasicBinder: OFF

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace # 파라미터 바인딩 로그 출력

# JWT 설정을 spring 섹션 외부로 이동시켰습니다.
jwt:
  secret: "c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK"
  expiration: 86400000 # 24시간 (밀리초 단위)

kafka:
  topics:
    reserve-seat-request: reserve-seat-request
    reserve-seat-success: reserve-seat-success
    reserve-seat-failure: reserve-seat-failure
    create-token-failure: create-token-failure
    seat-reservations-response : seat-reservations-response
    seat-reservations : seat-reservations
    user-queue-validation-topic:  user-queue-validation-topic
    add-waiting-queue-response: add-waiting-queue-response
    issued-token-request: issued-token-request
    issued-token-response: issued-token-response
    release-seat: release-seat
    reservation-out-box-request: reservation-out-box-request

testToken: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwicXVldWVPcmRlciI6MSwicmVtYWluaW5nVGltZSI6NjAwLCJzZWF0RGV0YWlsSWQiOjUsImlhdCI6MTcyOTYwNTIzOSwiZXhwIjoxNzYxMTYyODM5fQ.Ski_jMqgz2CzCYRFUpiDbTHluIUO6wJF2zOUpoO0NvjuwHfgiE_RgfEzJYsiQVj0vWf5XCcg5-m599GqW6_Bbg"
